FROM ubuntu:latest

RUN apt-get update && apt install -y \
	automake \
	autoconf \
	build-essential \
	cmake \
	curl \
	git \
	libomp-dev \
	libssl-dev \
	libtool \
	python3 \
	&& rm -rf /var/lib/apt/list/*